In [1]:
prices = []
N = 60*60*24*365
for i in range(N):
        prices.append(100 + i/100)
prices[:5]

[100.0, 100.01, 100.02, 100.03, 100.04]


In [2]:
avg = 0.0
for p in prices:
    avg += p
avg /= len(prices)
avg

157779.995


That worked, but was rather slow. What about numpy arrays?

In [3]:
import numpy as np

prices = 100 + np.arange(N)/100
prices[:5] 

[100.   100.01 100.02 100.03 100.04]


In [4]:
avg = np.mean(prices)
avg

157779.995


Blazingly fast! Mainly because numpy arrays are homogenous rather than normal python lists.

In [8]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

In [9]:
arr.ndim

1

In [10]:
arr.shape

(5,)

In [17]:
arr_2d = np.array(
    [
        [10, 20, 30, 40, 50],
        [100, 200, 300, 400, 500]
    ]
)
arr_2d

array([[ 10,  20,  30,  40,  50],
       [100, 200, 300, 400, 500]])

In [18]:
arr_2d.ndim

2

In [19]:
arr_2d.shape

(2, 5)

In [20]:
arr_2d.size

10

In [21]:
arr_2d.dtype

dtype('int64')

Two rules are present for numpy arrays:

- Every element must be the same type and size.
- If an array's elements are also arrays, the inner arrays must have same type and same number of elements as each other.